version: '2.3'
services:
  kobot:
    image: kobot_ros2_image
    build: .
    container_name: kobot_container
    command:  bash
    privileged: true
    stdin_open: true
    tty: true
    environment:
        - DISPLAY
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix:rw
        - ./catkin_ws:/root/catkin_ws
    network_mode: host
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /dev/video2:/dev/video2
      - /dev/video3:/dev/video3
      - /dev/video4:/dev/video4
      - /dev/video5:/dev/video5
      - /dev/media0:/dev/media0
      - /dev/media1:/dev/media1
    device_cgroup_rules:
      - 'c 81:* rmw'
      - 'c 189:* rmw'
